### PR TITLE
add julia to website

### PR DESCRIPTION
**Pull request by Jafagervik**
Issue: #20

### CODE REVIEW

**Review by jcbhmr — APPROVED** [review]
looks good! 👍

**Comment by jcbhmr** [comment]
oh and btw feel free to do things like prs or create new repos or whatever without me lol; I trust you know what you're doing 😉

other btw: don't forget to add julia to the .github readme that shows up on the @1brc org page 👍

**Comment by gcarreno** [comment]
Hey Jacob(@jcbhmr),

I wanted to follow suite and add the Julia image and link to the `.github` repo.
I had a look at the source and it's referencing the `assets` folder with some unique identifiers after it.

I guess that my search fu is rather crap, since I couldn't find a way to access that `assets` folder or understand where I could even copy/paste that image path.

Can you please give me a hand on this in order to make good with the last requirement to add Julia to the fray?

Many thanks in advance!!

Cheers,
Gus

**Comment by jcbhmr** [comment]
Sure! The images are copy-pasted directly into the GitHub editor UI which uploads them to githubs random-id CDN. For instance if you click the 📎Attach Files button in the "Add a comment" box in this thread and pick an image it will give you a https://*.githubusercontent.com URL where it stashed it.

If I copy paste a cat image from google (RClick + Paste in this text box) it will give me this:

```
![image](https://github.com/1brc/1brc.github.io/assets/61068799/6b23c0e9-5e97-458a-9a21-a9dfba41d207)
```

image

cool right! its like https://imgur.com/upload but built into github

**Pull request merged**
